[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
  framework = "create-react-app"
  targetPort = 3000
  autoLaunch = true
  publish = "build"

[[plugins]]
  package = "@netlify/plugin-emails"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
